### PR TITLE
add new features: (1) regional-based seeding (2) paint-with-word for image inpainting, and (3) gradio interface

### PR DESCRIPTION
**Pull request by lwchen6309**
(1) regional-based seeding
This is supported only for text-image synthesis

(2) paint-with-word for image inpainting
Combine paint-with-word with the algorithm of image inpainting in "StableDiffusionInpaintPipeline"

(3) gradio interface
This is currently supported only for image synthesis instead of image inpainting

update: paint-with-word now support mps device (Mac M1/M2 GPU)

### CODE REVIEW

**Comment by cloneofsimo** [comment]
Hey @lwchen6309 , thank you for this PR!

**Comment by cloneofsimo** [comment]
Ive checked your email. Once you are done with this PR, you can lmk and Ill merge, thanks again!

**Comment by lwchen6309** [comment]
Hi @cloneofsimo, thanks for your reply.
I finish this PR. Please merge it :)

**Comment by cloneofsimo** [comment]
Thank you so much again for your contribution!

**Pull request merged**
